swagger: "2.0"
info:
  description: "demo msg receiver"
  version: "1.0.0"
  title: "msg receiver"
host: "localhost"
basePath: "/msgs"
tags:
- name: "msg"
  description: "message body"
- name: "msgId"
  description: "message id"
schemes:
- "http"
paths:
  /msg:
    get:
      tags:
      - "msg"
      summary: "Find msg by ID"
      description: "Returns a single message"
      operationId: "getMsgById"
      produces:
      - "application/json"
      parameters:
      - name: "msgId"
        in: "path"
        description: "message ID"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/msg"
        400:
          description: "invalid ID supplied"
        404:
          description: "message not found"
    post:
      tags:
      - "msg"
      summary: "Add a new message"
      description: "Add a new message"
      operationId: "addMsg"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "msg"
        in: "query"
        description: ""
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/msg"
        400:
          description: "invalid ID supplied"
        404:
          description: "message not found"
    put:
      tags:
      - "msgId"
      - "msg"
      summary: "Update an existing message"
      description: ""
      operationId: "updateMsg"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "msg"
        in: "query"
        description: ""
        required: true
        type: "string"
      - name: "msgId"
        in: "path"
        description: "message ID"
        required: true
        type: "integer"
        format: "int64"
      responses:
        400:
          description: "Invalid ID supplied"
        404:
          description: "Msg not found"
        405:
          description: "Validation exception"
    delete:
      tags:
      - "msg"
      summary: "Deletes a messge"
      description: ""
      operationId: "deleteMsg"
      produces:
      - "application/json"
      parameters:
      - name: "msgId"
        in: "path"
        description: "message id to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        400:
          description: "Invalid username supplied"
        404:
          description: "User not found"
definitions:
  msg:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      message:
        type: "string"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"